// <auto-generated />
using System;
using Guildwise.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Guildwise.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(GuildwiseDbContext))]
    partial class GuildwiseDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Guildwise.Domain.Character", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CharacterClass")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("character_class");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Realm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("realm");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("region");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("character_role");

                    b.Property<string>("Specialization")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("character_specialization");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId", "Region", "Realm", "Name")
                        .IsUnique();

                    b.ToTable("characters", (string)null);
                });

            modelBuilder.Entity("Guildwise.Domain.Guild", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.Property<string>("Realm")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("realm");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("region");

                    b.HasKey("Id");

                    b.ToTable("guilds", (string)null);
                });

            modelBuilder.Entity("Guildwise.Domain.GuildMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.PrimitiveCollection<string[]>("AdditionalRoles")
                        .IsRequired()
                        .HasColumnType("text[]")
                        .HasColumnName("additional_roles");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid")
                        .HasColumnName("guild_id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<string>("Rank")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("guild_rank");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("GuildId", "PlayerId")
                        .IsUnique();

                    b.ToTable("guild_members", (string)null);
                });

            modelBuilder.Entity("Guildwise.Domain.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("display_name");

                    b.Property<Guid?>("MainCharacterId")
                        .HasColumnType("uuid")
                        .HasColumnName("main_character_id");

                    b.HasKey("Id");

                    b.HasIndex("MainCharacterId");

                    b.ToTable("players", (string)null);
                });

            modelBuilder.Entity("Guildwise.Domain.RaidTeam", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GuildId")
                        .HasColumnType("uuid")
                        .HasColumnName("guild_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("GuildId", "Name")
                        .IsUnique();

                    b.ToTable("raid_teams", (string)null);
                });

            modelBuilder.Entity("Guildwise.Domain.RaidTeamMember", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("PlayerId")
                        .HasColumnType("uuid")
                        .HasColumnName("player_id");

                    b.Property<Guid>("RaidTeamId")
                        .HasColumnType("uuid")
                        .HasColumnName("raid_team_id");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.HasIndex("RaidTeamId", "PlayerId")
                        .IsUnique();

                    b.ToTable("raid_team_members", (string)null);
                });

            modelBuilder.Entity("Guildwise.Domain.Character", b =>
                {
                    b.HasOne("Guildwise.Domain.Player", null)
                        .WithMany("Characters")
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Guildwise.Domain.GuildMember", b =>
                {
                    b.HasOne("Guildwise.Domain.Guild", null)
                        .WithMany("Members")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Guildwise.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("Guildwise.Domain.Player", b =>
                {
                    b.HasOne("Guildwise.Domain.Character", null)
                        .WithMany()
                        .HasForeignKey("MainCharacterId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("Guildwise.Domain.RaidTeam", b =>
                {
                    b.HasOne("Guildwise.Domain.Guild", null)
                        .WithMany("RaidTeams")
                        .HasForeignKey("GuildId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Guildwise.Domain.RaidTeamMember", b =>
                {
                    b.HasOne("Guildwise.Domain.Player", null)
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("Guildwise.Domain.RaidTeam", null)
                        .WithMany("Members")
                        .HasForeignKey("RaidTeamId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Guildwise.Domain.Guild", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("RaidTeams");
                });

            modelBuilder.Entity("Guildwise.Domain.Player", b =>
                {
                    b.Navigation("Characters");
                });

            modelBuilder.Entity("Guildwise.Domain.RaidTeam", b =>
                {
                    b.Navigation("Members");
                });
#pragma warning restore 612, 618
        }
    }
}
