namespace Guildwise.Domain;

public enum CharacterSpecialization
{
    Unknown = 0,
    DeathKnightBlood = 1,
    DeathKnightFrost = 2,
    DeathKnightUnholy = 3,
    DemonHunterHavoc = 4,
    DemonHunterVengeance = 5,
    DruidBalance = 6,
    DruidFeral = 7,
    DruidGuardian = 8,
    DruidRestoration = 9,
    EvokerAugmentation = 10,
    EvokerDevastation = 11,
    EvokerPreservation = 12,
    HunterBeastMastery = 13,
    HunterMarksmanship = 14,
    HunterSurvival = 15,
    MageArcane = 16,
    MageFire = 17,
    MageFrost = 18,
    MonkBrewmaster = 19,
    MonkMistweaver = 20,
    MonkWindwalker = 21,
    PaladinHoly = 22,
    PaladinProtection = 23,
    PaladinRetribution = 24,
    PriestDiscipline = 25,
    PriestHoly = 26,
    PriestShadow = 27,
    RogueAssassination = 28,
    RogueOutlaw = 29,
    RogueSubtlety = 30,
    ShamanElemental = 31,
    ShamanEnhancement = 32,
    ShamanRestoration = 33,
    WarlockAffliction = 34,
    WarlockDemonology = 35,
    WarlockDestruction = 36,
    WarriorArms = 37,
    WarriorFury = 38,
    WarriorProtection = 39
}
